"""
Sample data generator — creates realistic placeholder data for all indicators.
Includes rich descriptions, explainers, and projection sources for UI tooltips.
Run: python generate_sample_data.py
"""

import json, os, random, math

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "data", "processed")
os.makedirs(OUTPUT_DIR, exist_ok=True)

def save(data):
    path = os.path.join(OUTPUT_DIR, f"{data['id']}.json")
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"  ✓ {data['id']} ({len(data['series'])} points)")

def make_series(start_year, end_year, start_val, end_val,
                frequency="annual", noise=0.02, shape="linear",
                projection_start_year=2026):
    if frequency == "monthly":
        periods = [(y, m) for y in range(start_year, end_year+1) for m in range(1,13)]
        dfmt = lambda y,m: f"{y}-{m:02d}"
    elif frequency == "quarterly":
        periods = [(y, q) for y in range(start_year, end_year+1) for q in [3,6,9,12]]
        dfmt = lambda y,m: f"{y}-{m:02d}"
    else:
        periods = [(y,1) for y in range(start_year, end_year+1)]
        dfmt = lambda y,m: str(y)
    n = len(periods)
    series = []
    random.seed(42)
    for i,(y,m) in enumerate(periods):
        t = i/max(n-1,1)
        if shape == "linear":
            base = start_val + (end_val-start_val)*t
        elif shape == "exponential":
            base = start_val * math.exp(math.log(end_val/start_val)*t)
        elif shape == "boom_bust":
            peak = end_val*2.5
            base = start_val+(peak-start_val)*(t/0.6) if t<0.6 else peak-(peak-end_val)*((t-0.6)/0.4)
        elif shape == "volatile":
            base = start_val+(end_val-start_val)*t + math.sin(t*20)*(end_val-start_val)*0.3
        else:
            base = start_val+(end_val-start_val)*t
        value = max(0.01, base*(1+random.gauss(0,noise)))
        series.append({"date": dfmt(y,m), "value": round(value,2), "projected": y>=projection_start_year})
    return series

indicators = [

  # ── ECONOMY ────────────────────────────────────────────────────────────────

  {
    "id": "cash_rate",
    "label": "Cash rate",
    "category": "economy",
    "unit": "%", "unit_label": "%",
    "frequency": "monthly",
    "source": "RBA Table A2",
    "source_url": "https://www.rba.gov.au/statistics/tables/",
    "description": "The Reserve Bank of Australia's official cash rate target — the interest rate banks charge each other for overnight loans, which flows through to mortgages, savings accounts and the broader economy.",
    "explainer": "The cash rate is the RBA's primary lever for controlling inflation. When inflation is too high, the RBA raises rates to slow borrowing and spending. When the economy is weak, it cuts rates to stimulate activity. The rate hit 17.5% during the 1990 recession and 0.1% during Covid — a 60-year chart shows the full arc of Australia's monetary policy.",
    "projection_source": "RBA quarterly Statement on Monetary Policy. Market pricing via ASX 30-day interbank futures.",
    "first_year": 1990,
    "last_updated": "2026-04",
    "projection_start": "2026-01",
    "notes": "Prior to 1990 the cash rate was not formally targeted.",
    "series": [
      {"date":"1990-01","value":17.5,"projected":False},
      {"date":"1991-01","value":10.5,"projected":False},
      {"date":"1992-01","value":6.5,"projected":False},
      {"date":"1993-01","value":4.75,"projected":False},
      {"date":"1994-01","value":4.75,"projected":False},
      {"date":"1995-01","value":7.5,"projected":False},
      {"date":"1996-01","value":7.5,"projected":False},
      {"date":"1997-01","value":5.5,"projected":False},
      {"date":"1998-01","value":5.0,"projected":False},
      {"date":"1999-01","value":4.75,"projected":False},
      {"date":"2000-01","value":6.25,"projected":False},
      {"date":"2001-01","value":6.25,"projected":False},
      {"date":"2002-01","value":4.25,"projected":False},
      {"date":"2003-01","value":4.75,"projected":False},
      {"date":"2004-01","value":5.25,"projected":False},
      {"date":"2005-01","value":5.5,"projected":False},
      {"date":"2006-01","value":5.5,"projected":False},
      {"date":"2007-01","value":6.25,"projected":False},
      {"date":"2008-01","value":7.25,"projected":False},
      {"date":"2009-01","value":3.25,"projected":False},
      {"date":"2010-01","value":3.75,"projected":False},
      {"date":"2011-01","value":4.75,"projected":False},
      {"date":"2012-01","value":4.25,"projected":False},
      {"date":"2013-01","value":3.0,"projected":False},
      {"date":"2014-01","value":2.5,"projected":False},
      {"date":"2015-01","value":2.25,"projected":False},
      {"date":"2016-01","value":2.0,"projected":False},
      {"date":"2017-01","value":1.5,"projected":False},
      {"date":"2018-01","value":1.5,"projected":False},
      {"date":"2019-01","value":1.5,"projected":False},
      {"date":"2020-01","value":0.75,"projected":False},
      {"date":"2020-04","value":0.25,"projected":False},
      {"date":"2021-01","value":0.1,"projected":False},
      {"date":"2022-01","value":0.1,"projected":False},
      {"date":"2022-06","value":0.85,"projected":False},
      {"date":"2022-09","value":2.35,"projected":False},
      {"date":"2023-01","value":3.1,"projected":False},
      {"date":"2023-06","value":4.1,"projected":False},
      {"date":"2024-01","value":4.35,"projected":False},
      {"date":"2025-01","value":4.1,"projected":False},
      {"date":"2025-06","value":3.85,"projected":False},
      {"date":"2026-01","value":3.5,"projected":True},
      {"date":"2027-01","value":3.25,"projected":True},
      {"date":"2028-01","value":3.0,"projected":True},
    ],
  },

  {
    "id": "cpi",
    "label": "CPI",
    "category": "economy",
    "unit": "index", "unit_label": "",
    "frequency": "quarterly",
    "source": "ABS 6401.0",
    "source_url": "https://api.data.abs.gov.au/data/CPI",
    "description": "Consumer Price Index — measures the change in prices paid by Australian households for a fixed basket of goods and services. The RBA targets 2–3% annual CPI growth.",
    "explainer": "The CPI tracks the cost of a representative 'basket' of goods — groceries, rent, petrol, healthcare, education and more. When CPI rises faster than wages, living standards fall. The 2022–23 spike to 7.8% was the highest since 1990, driven by global supply chain disruptions, energy prices and post-Covid demand.",
    "projection_source": "RBA Statement on Monetary Policy. Projects CPI returning to 2–3% target band by mid-2026.",
    "first_year": 1975,
    "last_updated": "2026-03",
    "projection_start": "2026-01",
    "series": make_series(1975, 2035, 10, 185, "quarterly", noise=0.005, shape="exponential"),
  },

  {
    "id": "median_wage",
    "label": "Median wage",
    "category": "economy",
    "unit": "AUD", "unit_label": "$",
    "frequency": "annual",
    "source": "ABS 6310.0",
    "source_url": "https://www.abs.gov.au/statistics/labour/earnings-and-working-conditions",
    "description": "Median weekly earnings for full-time adult employees in Australia. This is the midpoint — half of workers earn more, half earn less.",
    "explainer": "Median wage is more representative than average wage, which is skewed upward by high earners. When compared with house prices or CPI, the median wage reveals changes in purchasing power and living standards. Real wages (adjusted for inflation) fell significantly in 2022–23 as inflation outpaced wage growth.",
    "projection_source": "Treasury Budget 2025–26. Assumes wage growth of 3.25% per year, moderating from recent peaks.",
    "first_year": 1975,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": make_series(1975, 2035, 180, 1800, "annual", noise=0.02, shape="exponential"),
  },

  {
    "id": "wage_price_index",
    "label": "Wage price index",
    "category": "economy",
    "unit": "index", "unit_label": "",
    "frequency": "quarterly",
    "source": "ABS 6345.0",
    "source_url": "https://api.data.abs.gov.au/data/WPI",
    "description": "The Wage Price Index measures changes in the price employers pay for labour, holding quality and quantity of work constant. Base: September 1997 = 100.",
    "explainer": "Unlike average earnings, the WPI is designed to measure pure price changes in wages — stripping out shifts in the composition of the workforce (e.g. more part-time workers) or hours worked. It's the RBA's preferred measure of wage growth. When WPI grows slower than CPI, workers are experiencing real wage cuts.",
    "projection_source": "RBA Statement on Monetary Policy. Projects WPI growth of ~3.4% in 2026, gradually moderating.",
    "first_year": 1997,
    "last_updated": "2026-03",
    "projection_start": "2026-01",
    "notes": "Series begins September 1997 when ABS commenced the WPI.",
    "series": make_series(1997, 2035, 65, 160, "quarterly", noise=0.005, shape="linear"),
  },

  {
    "id": "gdp_per_capita",
    "label": "GDP per capita",
    "category": "economy",
    "unit": "AUD", "unit_label": "$",
    "frequency": "annual",
    "source": "ABS 5206.0",
    "source_url": "https://api.data.abs.gov.au/data/NA_GDP",
    "description": "Gross Domestic Product divided by population — the most commonly used measure of average living standards and economic output per person.",
    "explainer": "GDP per capita measures the total value of goods and services produced in Australia divided by the number of people. It's an imperfect measure of wellbeing — it doesn't capture inequality, unpaid work, or environmental costs — but it's the standard international benchmark for comparing economies over time. Australia went 28 years without a recession (1991–2020), visible as sustained growth in this series.",
    "projection_source": "Treasury Intergenerational Report 2023 and Budget 2025–26.",
    "first_year": 1975,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": make_series(1975, 2035, 6000, 92000, "annual", noise=0.02, shape="exponential"),
  },

  {
    "id": "household_debt_ratio",
    "label": "Household debt to income",
    "category": "economy",
    "unit": "%", "unit_label": "%",
    "frequency": "quarterly",
    "source": "RBA Table E2",
    "source_url": "https://www.rba.gov.au/statistics/tables/",
    "description": "Total household debt (mortgages, personal loans, credit cards) as a percentage of annual household disposable income. Australia is consistently among the world's highest.",
    "explainer": "This ratio shows how much debt households carry relative to their income. A ratio of 200% means the average household owes two years' worth of income. Australia's ratio has grown from around 40% in the late 1970s to nearly 190% today — almost entirely driven by mortgage debt and rising house prices. This makes Australian households unusually sensitive to interest rate changes.",
    "projection_source": "RBA Financial Stability Review. Assumes gradual deleveraging as interest rates moderate and housing credit growth slows.",
    "first_year": 1977,
    "last_updated": "2026-03",
    "projection_start": "2026-01",
    "series": make_series(1977, 2035, 40, 185, "quarterly", noise=0.01, shape="exponential"),
  },

  {
    "id": "m2_money_supply",
    "label": "M2 money supply",
    "category": "economy",
    "unit": "AUD_bn", "unit_label": "$bn",
    "frequency": "monthly",
    "source": "RBA Table D3",
    "source_url": "https://www.rba.gov.au/statistics/tables/",
    "description": "Broad money supply (M3) — the total amount of money in the Australian economy, including physical currency, bank deposits, and other liquid assets. Measured in billions of dollars.",
    "explainer": "Money supply measures how much money is circulating in the economy. When the money supply grows faster than the economy, inflation typically follows — you can see this relationship clearly by overlaying M2 with CPI. The RBA influences money supply through interest rates and, during Covid, through quantitative easing (bond purchases). M2 more than doubled between 2009 and 2023.",
    "projection_source": "RBA monetary policy projections. Growth assumed to moderate in line with credit growth forecasts.",
    "first_year": 1977,
    "last_updated": "2026-04",
    "projection_start": "2026-01",
    "series": make_series(1977, 2035, 30, 3800, "monthly", noise=0.008, shape="exponential"),
  },

  {
    "id": "private_credit_growth",
    "label": "Private credit growth",
    "category": "economy",
    "unit": "%", "unit_label": "%",
    "frequency": "monthly",
    "source": "RBA Table D1",
    "source_url": "https://www.rba.gov.au/statistics/tables/",
    "description": "Annual growth rate of total private sector credit — money borrowed by households and businesses from financial institutions.",
    "explainer": "Credit growth is a leading indicator of economic activity and financial risk. Rapid credit growth (above 10% per year) often precedes asset price bubbles and financial instability. Australia saw credit growing at 15–20% per year during the mid-2000s housing boom. When credit growth collapses — as in 2019 — it signals a credit crunch that can drag on growth.",
    "projection_source": "RBA Statement on Monetary Policy credit aggregates projections.",
    "first_year": 1977,
    "last_updated": "2026-04",
    "projection_start": "2026-01",
    "series": make_series(1977, 2035, 12, 5, "monthly", noise=0.3, shape="volatile"),
  },

  {
    "id": "asx200",
    "label": "ASX 200",
    "category": "economy",
    "unit": "index", "unit_label": "",
    "frequency": "monthly",
    "source": "ASX / Yahoo Finance",
    "source_url": "https://finance.yahoo.com/quote/%5EAXJO",
    "description": "The S&P/ASX 200 index — tracks the performance of the 200 largest companies listed on the Australian Securities Exchange by market capitalisation.",
    "explainer": "The ASX 200 is Australia's primary share market benchmark, covering about 80% of Australian equity market capitalisation. It includes the big four banks, mining giants (BHP, Rio Tinto), and Supermarkets. Because Australian superannuation funds hold ~$3.5 trillion — largely in equities — the ASX directly affects the retirement savings of most Australians. The GFC crash (−54%), Covid crash (−37%), and subsequent recoveries are all visible.",
    "projection_source": "Consensus analyst forecasts. Note: share market projections are inherently uncertain — treat as indicative only.",
    "first_year": 1992,
    "last_updated": "2026-04",
    "projection_start": "2026-01",
    "series": make_series(1992, 2035, 1500, 9200, "monthly", noise=0.05, shape="exponential"),
  },

  {
    "id": "gold_aud",
    "label": "Gold spot price (AUD)",
    "category": "economy",
    "unit": "AUD", "unit_label": "$",
    "frequency": "monthly",
    "source": "RBA Table G5",
    "source_url": "https://www.rba.gov.au/statistics/tables/",
    "description": "Gold spot price in Australian dollars per troy ounce. Gold is widely regarded as a store of value and a safe-haven asset during times of economic or geopolitical uncertainty.",
    "explainer": "Gold tends to rise when investors are fearful — during the GFC, Covid, and Ukraine war, gold surged as investors fled to safety. In AUD terms, gold also benefits when the Australian dollar weakens (a falling AUD makes gold cheaper for foreign buyers and more expensive in local terms). Australia is the world's second-largest gold producer, so gold prices also affect mining sector revenues and the ASX.",
    "projection_source": "World Bank Commodity Price Forecasts. Gold price projections are highly uncertain.",
    "first_year": 1975,
    "last_updated": "2026-04",
    "projection_start": "2026-01",
    "series": make_series(1975, 2035, 160, 5200, "monthly", noise=0.05, shape="exponential"),
  },

  {
    "id": "terms_of_trade",
    "label": "Terms of trade",
    "category": "economy",
    "unit": "index", "unit_label": "",
    "frequency": "quarterly",
    "source": "ABS 5302.0 / RBA",
    "source_url": "https://www.rba.gov.au/statistics/tables/",
    "description": "The ratio of export prices to import prices — how much imports Australia can purchase with a given volume of exports. A rising index means Australia's exports are becoming more valuable relative to what it imports.",
    "explainer": "Australia's terms of trade tell the story of the China relationship. When China's demand for iron ore, coal and LNG surged in the 2000s, Australian commodity prices soared — the terms of trade hit a 140-year high in 2011. This 'mining boom' funded government surpluses, kept unemployment low, and insulated Australia from the GFC. The subsequent bust (2011–2016) was equally dramatic. This is one of the most geopolitically revealing charts in the dataset.",
    "projection_source": "RBA Statement on Monetary Policy commodity price forecasts.",
    "first_year": 1975,
    "last_updated": "2026-03",
    "projection_start": "2026-01",
    "series": make_series(1975, 2035, 60, 90, "quarterly", noise=0.04, shape="boom_bust"),
  },

  # ── HOUSING ─────────────────────────────────────────────────────────────────

  {
    "id": "median_house_price",
    "label": "Median house price",
    "category": "housing",
    "unit": "AUD", "unit_label": "$",
    "frequency": "quarterly",
    "source": "ABS 6416.0",
    "source_url": "https://api.data.abs.gov.au/data/RPPI",
    "description": "Median residential property price across Australia's 8 capital cities, weighted average. Half of properties sell above this price, half below.",
    "explainer": "Australian house prices have risen faster than almost any comparable nation over the past 30 years. The median house price has increased roughly 30-fold since 1975 while median wages have grown around 10-fold — meaning homes now cost far more relative to income than they did a generation ago. The price-to-income ratio is now among the highest in the world. Key drivers include negative gearing tax policy, low interest rates, supply constraints, and population growth.",
    "projection_source": "Treasury and RBA housing market projections. CoreLogic consensus forecasts.",
    "first_year": 1975,
    "last_updated": "2026-03",
    "projection_start": "2026-01",
    "series": make_series(1975, 2035, 34000, 1250000, "quarterly", noise=0.02, shape="exponential"),
  },

  {
    "id": "rental_vacancy",
    "label": "Rental vacancy rate",
    "category": "housing",
    "unit": "%", "unit_label": "%",
    "frequency": "quarterly",
    "source": "REIA",
    "source_url": "https://www.reia.com.au",
    "description": "The percentage of rental properties currently vacant and available for rent. A healthy rental market is typically considered to have a vacancy rate of around 3%.",
    "explainer": "Rental vacancy is the most direct measure of rental market stress. When vacancy falls below 1% — as it did in 2022–23 in most Australian cities — renters face intense competition, rapidly rising rents, and difficulty securing housing. The post-Covid spike in net migration and slow housing construction combined to push vacancy to record lows. A rate below 1% is considered a rental crisis.",
    "projection_source": "REIA and PropTrack forecasts. Assumes gradual recovery as new housing supply comes online.",
    "first_year": 1980,
    "last_updated": "2026-03",
    "projection_start": "2026-01",
    "series": make_series(1980, 2035, 3.5, 1.0, "quarterly", noise=0.15, shape="linear"),
  },

  {
    "id": "housing_approvals",
    "label": "Housing approvals",
    "category": "housing",
    "unit": "count", "unit_label": "",
    "frequency": "monthly",
    "source": "ABS 8731.0",
    "source_url": "https://api.data.abs.gov.au/data/BA",
    "description": "Monthly number of new residential dwelling building approvals issued by local councils — a leading indicator of future housing supply.",
    "explainer": "Building approvals lead actual construction by 12–18 months, making this a useful forward indicator of housing supply. Australia needs approximately 240,000 new homes per year to meet population growth and the government's Housing Accord target — recent approvals have consistently fallen short. When approvals collapse (as in 2023 due to construction cost pressures), a supply shortage follows 1–2 years later.",
    "projection_source": "HIA and Master Builders Australia housing forecasts.",
    "first_year": 1983,
    "last_updated": "2026-04",
    "projection_start": "2026-01",
    "series": make_series(1983, 2035, 10000, 14000, "monthly", noise=0.15, shape="volatile"),
  },

  # ── DEMOGRAPHICS ────────────────────────────────────────────────────────────

  {
    "id": "population",
    "label": "Total population",
    "category": "demographics",
    "unit": "count", "unit_label": "",
    "frequency": "annual",
    "source": "ABS 3101.0",
    "source_url": "https://api.data.abs.gov.au/data/ERP",
    "description": "Estimated Resident Population of Australia — the total number of people living in Australia at a given time, including citizens, permanent residents and long-term visitors.",
    "explainer": "Australia's population has more than doubled since 1975, from around 13.5 million to over 27 million today. This growth is primarily driven by net overseas migration rather than natural increase (births minus deaths). Population growth drives demand for housing, infrastructure, healthcare and education — overlaying population with house prices or housing approvals reveals key supply/demand dynamics.",
    "projection_source": "ABS Population Projections (Series B — medium growth). Treasury Intergenerational Report 2023 projects ~40 million by 2063.",
    "first_year": 1975,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": make_series(1975, 2035, 13500000, 30000000, "annual", noise=0.002, shape="linear"),
  },

  {
    "id": "net_migration",
    "label": "Net overseas migration",
    "category": "demographics",
    "unit": "count", "unit_label": "",
    "frequency": "annual",
    "source": "ABS 3101.0",
    "source_url": "https://api.data.abs.gov.au/data/NOM",
    "description": "Net overseas migration — the number of people arriving in Australia to stay 12+ months, minus those leaving. Includes skilled migrants, international students, working holiday makers and humanitarian entrants.",
    "explainer": "Net migration = long-term arrivals minus long-term departures. The post-Covid spike to ~548,000 in 2022–23 reflects Australia reopening its borders, a backlog of approximately 1 million visa applications that accumulated during closure, and a surge in international students. The negative figure in 2020 reflects border closures. Migration is Australia's primary population growth driver and has an outsized effect on housing demand — the 2022–23 spike arriving into an already undersupplied rental market directly caused the rental crisis.",
    "projection_source": "Treasury Intergenerational Report 2023. Projects net migration moderating to approximately 235,000 per year by 2026, remaining elevated relative to the pre-Covid average of around 200,000.",
    "first_year": 1976,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": [
      {"date":"1976","value":52000,"projected":False},
      {"date":"1977","value":48000,"projected":False},
      {"date":"1978","value":45000,"projected":False},
      {"date":"1979","value":55000,"projected":False},
      {"date":"1980","value":87000,"projected":False},
      {"date":"1981","value":95000,"projected":False},
      {"date":"1982","value":75000,"projected":False},
      {"date":"1983","value":42000,"projected":False},
      {"date":"1984","value":68000,"projected":False},
      {"date":"1985","value":92000,"projected":False},
      {"date":"1986","value":97000,"projected":False},
      {"date":"1987","value":110000,"projected":False},
      {"date":"1988","value":145000,"projected":False},
      {"date":"1989","value":148000,"projected":False},
      {"date":"1990","value":121000,"projected":False},
      {"date":"1991","value":74000,"projected":False},
      {"date":"1992","value":52000,"projected":False},
      {"date":"1993","value":45000,"projected":False},
      {"date":"1994","value":68000,"projected":False},
      {"date":"1995","value":82000,"projected":False},
      {"date":"1996","value":85000,"projected":False},
      {"date":"1997","value":72000,"projected":False},
      {"date":"1998","value":77000,"projected":False},
      {"date":"1999","value":95000,"projected":False},
      {"date":"2000","value":107000,"projected":False},
      {"date":"2001","value":115000,"projected":False},
      {"date":"2002","value":118000,"projected":False},
      {"date":"2003","value":110000,"projected":False},
      {"date":"2004","value":120000,"projected":False},
      {"date":"2005","value":132000,"projected":False},
      {"date":"2006","value":158000,"projected":False},
      {"date":"2007","value":177000,"projected":False},
      {"date":"2008","value":215000,"projected":False},
      {"date":"2009","value":228000,"projected":False},
      {"date":"2010","value":180000,"projected":False},
      {"date":"2011","value":168000,"projected":False},
      {"date":"2012","value":178000,"projected":False},
      {"date":"2013","value":195000,"projected":False},
      {"date":"2014","value":185000,"projected":False},
      {"date":"2015","value":168000,"projected":False},
      {"date":"2016","value":182000,"projected":False},
      {"date":"2017","value":240000,"projected":False},
      {"date":"2018","value":232000,"projected":False},
      {"date":"2019","value":239000,"projected":False},
      {"date":"2020","value":-97000,"projected":False},
      {"date":"2021","value":11000,"projected":False},
      {"date":"2022","value":387000,"projected":False},
      {"date":"2023","value":548000,"projected":False},
      {"date":"2024","value":395000,"projected":False},
      {"date":"2025","value":310000,"projected":False},
      {"date":"2026","value":260000,"projected":True},
      {"date":"2027","value":245000,"projected":True},
      {"date":"2028","value":240000,"projected":True},
      {"date":"2029","value":238000,"projected":True},
      {"date":"2030","value":235000,"projected":True},
      {"date":"2031","value":235000,"projected":True},
      {"date":"2032","value":235000,"projected":True},
      {"date":"2033","value":235000,"projected":True},
      {"date":"2034","value":235000,"projected":True},
      {"date":"2035","value":235000,"projected":True},
    ],
  },

  {
    "id": "median_age",
    "label": "Median age",
    "category": "demographics",
    "unit": "years", "unit_label": " yrs",
    "frequency": "annual",
    "source": "ABS 3101.0",
    "source_url": "https://api.data.abs.gov.au/data/ERP",
    "description": "The median age of the Australian population — half the population is older than this, half is younger. A rising median age signals an ageing population.",
    "explainer": "Australia's median age has risen from 27 in 1975 to around 38 today, reflecting falling birth rates and longer life expectancy. An ageing population increases demand for healthcare and aged care, puts pressure on the pension system (fewer workers supporting more retirees), and is one of the reasons Australia relies on migration to sustain its workforce. The dependency ratio chart shows the fiscal consequence of this trend.",
    "projection_source": "ABS Population Projections Series B. Treasury Intergenerational Report 2023.",
    "first_year": 1975,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": make_series(1975, 2035, 27, 42, "annual", noise=0.003, shape="linear"),
  },

  # ── WELLBEING ───────────────────────────────────────────────────────────────

  {
    "id": "unemployment",
    "label": "Unemployment rate",
    "category": "wellbeing",
    "unit": "%", "unit_label": "%",
    "frequency": "monthly",
    "source": "ABS 6202.0",
    "source_url": "https://api.data.abs.gov.au/data/LF",
    "description": "The percentage of the labour force who are unemployed and actively seeking work. Seasonally adjusted.",
    "explainer": "The unemployment rate is one of the most watched economic indicators — governments live and die by it politically. Australia's rate peaked at 11.2% during the 1990–91 recession and fell to a 50-year low of 3.4% in 2023. Note that the official rate undercounts labour market distress — it excludes 'underemployed' workers (those working fewer hours than they want) and people who have given up looking. The underemployment rate is typically 2–3x higher.",
    "projection_source": "RBA Statement on Monetary Policy. Projects unemployment rising moderately to 4.5% by end 2026 as the economy slows.",
    "first_year": 1978,
    "last_updated": "2026-04",
    "projection_start": "2026-01",
    "series": make_series(1978, 2035, 6.5, 4.2, "monthly", noise=0.12, shape="volatile"),
  },

  {
    "id": "life_expectancy",
    "label": "Life expectancy",
    "category": "wellbeing",
    "unit": "years", "unit_label": " yrs",
    "frequency": "annual",
    "source": "AIHW / ABS",
    "source_url": "https://www.aihw.gov.au/reports/life-expectancy-death",
    "description": "Life expectancy at birth, total persons — the average number of years a newborn would live if current mortality rates applied throughout their life.",
    "explainer": "Australia has one of the highest life expectancies in the world, rising from 71 years in 1975 to 83.4 years today. This reflects improvements in healthcare, reduced smoking rates, better nutrition and lower rates of workplace accidents. However, Covid caused a slight dip in 2021. There are significant disparities — Aboriginal and Torres Strait Islander Australians have a life expectancy roughly 8 years lower than the national average.",
    "projection_source": "Treasury Intergenerational Report 2023. Projects life expectancy reaching 89 years for men and 91 years for women by 2063.",
    "first_year": 1975,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": make_series(1975, 2035, 71.5, 86.5, "annual", noise=0.002, shape="linear"),
  },

  {
    "id": "suicide_rate",
    "label": "Suicide rate (per 100k)",
    "category": "wellbeing",
    "unit": "per_100k", "unit_label": "",
    "frequency": "annual",
    "source": "AIHW",
    "source_url": "https://www.aihw.gov.au/suicide-self-harm-monitoring",
    "description": "Age-standardised suicide rate per 100,000 population. Age-standardisation allows meaningful comparison over time as the population ages.",
    "explainer": "Around 3,200 Australians die by suicide each year — more than double the road toll. The rate has been relatively stable (10–13 per 100,000) since the 1990s after peaking in the early 1980s. Males account for approximately 75% of deaths. Overlaying suicide rate with unemployment, economic recessions and other wellbeing indicators can reveal correlations between economic stress and mental health outcomes. Data is typically released 12–18 months after the reference year.",
    "projection_source": "AIHW trend projections based on historical rates. Note: mental health outcomes are difficult to project and sensitive to policy interventions.",
    "first_year": 1980,
    "last_updated": "2024",
    "projection_start": "2026",
    "series": make_series(1980, 2035, 11.5, 10.8, "annual", noise=0.05, shape="volatile"),
  },

  {
    "id": "homelessness",
    "label": "Homelessness (per 100k)",
    "category": "wellbeing",
    "unit": "per_100k", "unit_label": "",
    "frequency": "annual",
    "source": "AIHW / ABS Census",
    "source_url": "https://www.aihw.gov.au/homelessness",
    "description": "Number of people experiencing homelessness per 100,000 population, as measured by the ABS Census. Includes rough sleepers, people in temporary accommodation, and those in severely overcrowded dwellings.",
    "explainer": "The ABS definition of homelessness is broader than 'sleeping rough' — it includes people in boarding houses, couch-surfing, staying in overcrowded homes and those in temporary shelters. On census night 2021, approximately 122,000 Australians were homeless (around 47 per 100,000). Homelessness is driven by a complex mix of housing affordability, mental health, domestic violence and substance use. Data is only available every 5 years (census) and interpolated between counts.",
    "projection_source": "AIHW and Homelessness Australia projections. Based on current housing stress trends and government policy settings.",
    "first_year": 2001,
    "last_updated": "2021",
    "projection_start": "2026",
    "notes": "Census-derived, available every 5 years (2001, 2006, 2011, 2016, 2021). Interpolated between census years.",
    "series": make_series(2001, 2035, 42, 57, "annual", noise=0.03, shape="linear"),
  },

  {
    "id": "gini_coefficient",
    "label": "Gini coefficient",
    "category": "wellbeing",
    "unit": "index", "unit_label": "",
    "frequency": "annual",
    "source": "OECD / ABS",
    "source_url": "https://stats.oecd.org",
    "description": "A measure of income inequality within Australia. Ranges from 0 (perfect equality — everyone earns the same) to 1 (maximum inequality — one person earns everything). Australia's Gini is typically around 0.32–0.34.",
    "explainer": "The Gini coefficient is the standard international measure of income inequality. A score of 0 means every person has identical income; a score of 1 means one person has all the income. Australia sits in the middle of OECD nations — less equal than the Nordics (around 0.27) but more equal than the US (0.39). Australia's Gini has risen gradually since the 1980s, reflecting higher returns to capital versus labour. Overlaying with wage growth and house prices reveals who captured the gains of economic growth.",
    "projection_source": "OECD distributional database projections. Assumes current policy settings continue.",
    "first_year": 1981,
    "last_updated": "2024",
    "projection_start": "2026",
    "series": make_series(1981, 2035, 0.28, 0.34, "annual", noise=0.02, shape="linear"),
  },

  {
    "id": "prison_population",
    "label": "Prison population (per 100k)",
    "category": "wellbeing",
    "unit": "per_100k", "unit_label": "",
    "frequency": "annual",
    "source": "ABS 4517.0",
    "source_url": "https://www.abs.gov.au/statistics/people/crime-and-justice",
    "description": "Number of prisoners per 100,000 adult population. Includes sentenced prisoners and those on remand awaiting trial.",
    "explainer": "Australia's imprisonment rate has more than doubled since the 1980s, from around 80 per 100,000 to over 220 — despite crime rates broadly falling over the same period. This reflects tougher sentencing laws, mandatory minimums, and a rise in remand (people held without sentence). Aboriginal and Torres Strait Islander Australians are imprisoned at 15 times the rate of non-Indigenous Australians. Prison costs exceed $120,000 per prisoner per year.",
    "projection_source": "AIHW and state corrections department projections.",
    "first_year": 1982,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": make_series(1982, 2035, 80, 230, "annual", noise=0.03, shape="linear"),
  },

  # ── GOVERNMENT ──────────────────────────────────────────────────────────────

  {
    "id": "net_govt_debt",
    "label": "Net government debt % GDP",
    "category": "government",
    "unit": "%", "unit_label": "%",
    "frequency": "annual",
    "source": "Treasury MYEFO / Budget",
    "source_url": "https://budget.gov.au",
    "description": "Australian Federal Government net debt as a percentage of GDP. Net debt = gross debt minus financial assets held by government (cash, investments). Expressed as % of GDP for comparability across time.",
    "explainer": "Net debt subtracts government financial assets (superannuation fund investments, cash holdings) from gross borrowings — giving a more accurate picture of the government's true liability. Expressing it as % of GDP adjusts for the fact that a larger economy can carry more debt. Australia ran net surpluses (negative net debt) through the Howard years, then took on significant debt post-GFC (stimulus spending) and again post-Covid. At around 22% of GDP, Australia's net debt is low by international standards — the US is above 100%, Japan above 160%.",
    "projection_source": "Treasury Budget 2025–26 and Medium Term Projections. Projects net debt peaking around 24% of GDP before gradually declining.",
    "first_year": 1975,
    "last_updated": "2026",
    "projection_start": "2026",
    "series": make_series(1975, 2035, 8, 42, "annual", noise=0.05, shape="volatile"),
  },

  {
    "id": "gross_govt_debt",
    "label": "Gross government debt ($bn)",
    "category": "government",
    "unit": "AUD_bn", "unit_label": "$bn",
    "frequency": "annual",
    "source": "Treasury MYEFO / AOFM",
    "source_url": "https://www.aofm.gov.au",
    "description": "Total face value of Australian Federal Government debt on issue, in billions of dollars. Unlike net debt, this does not subtract government financial assets.",
    "explainer": "Gross debt is the total amount the Australian government has borrowed — the face value of all Commonwealth Government Securities (bonds) on issue, managed by the Australian Office of Financial Management (AOFM). It only goes up over time in dollar terms, which makes it more alarming-looking than net debt but less analytically meaningful. Australia's gross debt crossed $1 trillion for the first time in 2023. Compare with net debt (% of GDP) for context — the gross figure needs to be seen alongside the assets held against it.",
    "projection_source": "AOFM borrowing program and Treasury Budget projections 2025–26.",
    "first_year": 1975,
    "last_updated": "2026",
    "projection_start": "2026",
    "notes": "Gross debt does not subtract government financial assets. For a more meaningful measure of fiscal position, see Net Government Debt % GDP.",
    "series": [
      {"date":"1975","value":12,"projected":False},
      {"date":"1980","value":28,"projected":False},
      {"date":"1985","value":67,"projected":False},
      {"date":"1990","value":95,"projected":False},
      {"date":"1995","value":189,"projected":False},
      {"date":"1996","value":196,"projected":False},
      {"date":"1997","value":179,"projected":False},
      {"date":"1998","value":162,"projected":False},
      {"date":"1999","value":143,"projected":False},
      {"date":"2000","value":123,"projected":False},
      {"date":"2001","value":115,"projected":False},
      {"date":"2002","value":107,"projected":False},
      {"date":"2003","value":98,"projected":False},
      {"date":"2004","value":90,"projected":False},
      {"date":"2005","value":82,"projected":False},
      {"date":"2006","value":74,"projected":False},
      {"date":"2007","value":66,"projected":False},
      {"date":"2008","value":58,"projected":False},
      {"date":"2009","value":135,"projected":False},
      {"date":"2010","value":228,"projected":False},
      {"date":"2011","value":285,"projected":False},
      {"date":"2012","value":326,"projected":False},
      {"date":"2013","value":368,"projected":False},
      {"date":"2014","value":425,"projected":False},
      {"date":"2015","value":471,"projected":False},
      {"date":"2016","value":518,"projected":False},
      {"date":"2017","value":551,"projected":False},
      {"date":"2018","value":564,"projected":False},
      {"date":"2019","value":575,"projected":False},
      {"date":"2020","value":703,"projected":False},
      {"date":"2021","value":834,"projected":False},
      {"date":"2022","value":895,"projected":False},
      {"date":"2023","value":978,"projected":False},
      {"date":"2024","value":1020,"projected":False},
      {"date":"2025","value":1065,"projected":False},
      {"date":"2026","value":1098,"projected":True},
      {"date":"2027","value":1124,"projected":True},
      {"date":"2028","value":1145,"projected":True},
      {"date":"2029","value":1162,"projected":True},
      {"date":"2030","value":1175,"projected":True},
      {"date":"2031","value":1185,"projected":True},
      {"date":"2032","value":1190,"projected":True},
      {"date":"2033","value":1193,"projected":True},
      {"date":"2034","value":1195,"projected":True},
      {"date":"2035","value":1196,"projected":True},
    ],
  },

  {
    "id": "public_servants",
    "label": "Total public sector employees",
    "category": "government",
    "unit": "count", "unit_label": "",
    "frequency": "annual",
    "source": "ABS 6248.0 Public Sector Employment and Earnings",
    "source_url": "https://www.abs.gov.au/statistics/labour/employment-and-unemployment/public-sector-employment-and-earnings/latest-release",
    "description": "Total public sector employee jobs across all levels of government — federal (Commonwealth), state/territory, and local government. Includes defence personnel, teachers, nurses, police, public administrators and all other government employees.",
    "explainer": "This is the complete picture of government employment — not just the ~185,000 federal public servants (APS) that get most political attention, but all 2.5 million Australians employed by government at every level. State governments are the largest employer (77%), covering teachers, nurses, police and emergency services. The Commonwealth accounts for 15%, and local government 8%. The number has grown substantially since the 1970s, driven largely by the expansion of healthcare (NDIS, aged care), education and disability services. As a share of the workforce it has remained relatively stable at around 15–16%, below the OECD average of 18%.",
    "projection_source": "Treasury Budget projections and ABS workforce projections. Assumes continued growth in health and disability services.",
    "first_year": 1975,
    "last_updated": "2025",
    "projection_start": "2026",
    "notes": "All levels of government: Commonwealth, state/territory and local. Includes defence personnel. ABS confirmed 2,517,900 in June 2024. Pre-1990 figures estimated from historical ABS and OECD sources.",
    "series": [
      {"date":"1975","value":1050000,"projected":False},
      {"date":"1976","value":1080000,"projected":False},
      {"date":"1977","value":1110000,"projected":False},
      {"date":"1978","value":1130000,"projected":False},
      {"date":"1979","value":1160000,"projected":False},
      {"date":"1980","value":1195000,"projected":False},
      {"date":"1981","value":1240000,"projected":False},
      {"date":"1982","value":1280000,"projected":False},
      {"date":"1983","value":1310000,"projected":False},
      {"date":"1984","value":1330000,"projected":False},
      {"date":"1985","value":1350000,"projected":False},
      {"date":"1986","value":1375000,"projected":False},
      {"date":"1987","value":1390000,"projected":False},
      {"date":"1988","value":1410000,"projected":False},
      {"date":"1989","value":1440000,"projected":False},
      {"date":"1990","value":1460000,"projected":False},
      {"date":"1991","value":1445000,"projected":False},
      {"date":"1992","value":1420000,"projected":False},
      {"date":"1993","value":1400000,"projected":False},
      {"date":"1994","value":1390000,"projected":False},
      {"date":"1995","value":1395000,"projected":False},
      {"date":"1996","value":1380000,"projected":False},
      {"date":"1997","value":1345000,"projected":False},
      {"date":"1998","value":1320000,"projected":False},
      {"date":"1999","value":1310000,"projected":False},
      {"date":"2000","value":1315000,"projected":False},
      {"date":"2001","value":1330000,"projected":False},
      {"date":"2002","value":1355000,"projected":False},
      {"date":"2003","value":1385000,"projected":False},
      {"date":"2004","value":1420000,"projected":False},
      {"date":"2005","value":1460000,"projected":False},
      {"date":"2006","value":1510000,"projected":False},
      {"date":"2007","value":1560000,"projected":False},
      {"date":"2008","value":1620000,"projected":False},
      {"date":"2009","value":1680000,"projected":False},
      {"date":"2010","value":1730000,"projected":False},
      {"date":"2011","value":1775000,"projected":False},
      {"date":"2012","value":1800000,"projected":False},
      {"date":"2013","value":1810000,"projected":False},
      {"date":"2014","value":1805000,"projected":False},
      {"date":"2015","value":1820000,"projected":False},
      {"date":"2016","value":1850000,"projected":False},
      {"date":"2017","value":1890000,"projected":False},
      {"date":"2018","value":1940000,"projected":False},
      {"date":"2019","value":1990000,"projected":False},
      {"date":"2020","value":2050000,"projected":False},
      {"date":"2021","value":2150000,"projected":False},
      {"date":"2022","value":2348000,"projected":False},
      {"date":"2023","value":2432000,"projected":False},
      {"date":"2024","value":2518000,"projected":False},
      {"date":"2025","value":2598000,"projected":False},
      {"date":"2026","value":2660000,"projected":True},
      {"date":"2027","value":2720000,"projected":True},
      {"date":"2028","value":2780000,"projected":True},
      {"date":"2029","value":2830000,"projected":True},
      {"date":"2030","value":2880000,"projected":True},
      {"date":"2031","value":2920000,"projected":True},
      {"date":"2032","value":2960000,"projected":True},
      {"date":"2033","value":3000000,"projected":True},
      {"date":"2034","value":3040000,"projected":True},
      {"date":"2035","value":3080000,"projected":True},
    ],
  },

  # ── ENVIRONMENT ─────────────────────────────────────────────────────────────

  {
    "id": "co2_emissions",
    "label": "CO₂ emissions (Mt)",
    "category": "environment",
    "unit": "Mt", "unit_label": " Mt",
    "frequency": "annual",
    "source": "DCCEEW",
    "source_url": "https://www.dcceew.gov.au/climate-change/publications/national-greenhouse-gas-inventory",
    "description": "Australia's total net greenhouse gas emissions in megatonnes of CO₂ equivalent per year, covering all sectors including energy, agriculture, transport and land use.",
    "explainer": "Australia is one of the world's largest per-capita greenhouse gas emitters due to its coal-heavy electricity grid, large mining sector and agriculture. Emissions peaked around 2007 and have since declined, driven by the growth of rooftop solar, wind power, and the closure of coal-fired power stations. Australia has committed to net zero by 2050 and a 43% reduction by 2030 relative to 2005 levels. The emissions trajectory is one of the most contested political charts in this dataset.",
    "projection_source": "DCCEEW Emissions Projections 2024. Based on current policies — does not assume additional climate action beyond legislated measures.",
    "first_year": 1990,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": make_series(1990, 2035, 420, 280, "annual", noise=0.02, shape="linear"),
  },

  {
    "id": "renewable_energy",
    "label": "Renewable energy %",
    "category": "environment",
    "unit": "%", "unit_label": "%",
    "frequency": "annual",
    "source": "AEMO / Clean Energy Regulator",
    "source_url": "https://www.aemo.com.au",
    "description": "Renewable energy as a percentage of total electricity generation from the National Electricity Market (NEM). Includes wind, solar (utility and rooftop), hydro and other renewables.",
    "explainer": "Australia's renewable energy share has grown dramatically — from around 8% in 2001 to over 35% in 2025 — driven primarily by rooftop solar (Australia has the world's highest uptake per capita) and large-scale wind and solar farms. The government's target is 82% renewables by 2030. Overlaying this with CO₂ emissions and electricity prices reveals the energy transition story — renewables are now the cheapest form of new generation in Australia.",
    "projection_source": "AEMO Integrated System Plan 2024 Central Scenario. Government target: 82% by 2030.",
    "first_year": 2001,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": make_series(2001, 2035, 8, 72, "annual", noise=0.03, shape="exponential"),
  },

  {
    "id": "temp_anomaly",
    "label": "Avg temperature anomaly",
    "category": "environment",
    "unit": "°C", "unit_label": "°C",
    "frequency": "annual",
    "source": "Bureau of Meteorology",
    "source_url": "http://www.bom.gov.au/climate/change/",
    "description": "Annual mean temperature anomaly for Australia relative to the 1961–1990 baseline average. A positive value means that year was warmer than the historical average.",
    "explainer": "Australia's average temperature has risen approximately 1.5°C since reliable records began in 1910. The anomaly is measured against the 1961–1990 baseline — so a reading of +1.5°C means that year was 1.5 degrees warmer than the average of those decades. Every decade since the 1950s has been warmer than the previous one. The 2019–20 bushfire season coincided with Australia's hottest and driest year on record (anomaly of +1.9°C). This is one of the most unambiguous trends in the entire dataset.",
    "projection_source": "CSIRO and BOM State of the Climate 2024. Projects continued warming of 1–2.5°C by 2060 depending on global emissions pathways.",
    "first_year": 1975,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": make_series(1975, 2035, -0.2, 1.8, "annual", noise=0.3, shape="linear"),
  },
  # ── DERIVED: Price-to-income ratio ─────────────────────────────────────
  {
    "id": "price_to_income",
    "label": "House price-to-income ratio",
    "category": "housing",
    "unit": "ratio", "unit_label": "x",
    "frequency": "annual",
    "source": "ABS 6416.0 + ABS 6302.0 (derived)",
    "source_url": "https://www.abs.gov.au",
    "description": "Median house price divided by median annual household income — how many years of income it takes to buy a typical home. A ratio of 3x was historically considered affordable; above 5x is severely unaffordable.",
    "explainer": "In the 1980s, a typical Australian home cost around 3 times the annual median wage. Today it exceeds 10x nationally — meaning the average worker would need to save their entire income for a decade to buy the median home. No other chart better illustrates the generational wealth shift between those who bought before 2000 and those who didnt. Overlay with net migration, interest rates and housing approvals to see the full picture.",
    "projection_source": "Derived from Treasury housing affordability projections and RBA mortgage stress analysis. Assumes moderate house price and wage growth per Budget 2025-26.",
    "first_year": 1975,
    "last_updated": "2025",
    "projection_start": "2026",
    "notes": "Derived metric: median house price / median annual household income.",
    "series": [
      {"date":"1975","value":3.1,"projected":False},
      {"date":"1980","value":3.2,"projected":False},
      {"date":"1985","value":3.3,"projected":False},
      {"date":"1990","value":4.0,"projected":False},
      {"date":"1995","value":3.6,"projected":False},
      {"date":"2000","value":4.5,"projected":False},
      {"date":"2001","value":4.8,"projected":False},
      {"date":"2002","value":5.3,"projected":False},
      {"date":"2003","value":5.9,"projected":False},
      {"date":"2004","value":6.2,"projected":False},
      {"date":"2005","value":6.1,"projected":False},
      {"date":"2006","value":6.3,"projected":False},
      {"date":"2007","value":6.6,"projected":False},
      {"date":"2008","value":6.4,"projected":False},
      {"date":"2009","value":6.7,"projected":False},
      {"date":"2010","value":7.1,"projected":False},
      {"date":"2011","value":6.9,"projected":False},
      {"date":"2012","value":6.7,"projected":False},
      {"date":"2013","value":6.8,"projected":False},
      {"date":"2014","value":7.2,"projected":False},
      {"date":"2015","value":7.8,"projected":False},
      {"date":"2016","value":8.1,"projected":False},
      {"date":"2017","value":8.5,"projected":False},
      {"date":"2018","value":8.2,"projected":False},
      {"date":"2019","value":7.9,"projected":False},
      {"date":"2020","value":8.1,"projected":False},
      {"date":"2021","value":9.2,"projected":False},
      {"date":"2022","value":9.8,"projected":False},
      {"date":"2023","value":10.1,"projected":False},
      {"date":"2024","value":10.4,"projected":False},
      {"date":"2025","value":10.6,"projected":False},
      {"date":"2026","value":10.5,"projected":True},
      {"date":"2030","value":9.8,"projected":True},
      {"date":"2035","value":9.5,"projected":True},
    ],
  },

  # ── DERIVED: Underemployment rate ───────────────────────────────────────
  {
    "id": "underemployment",
    "label": "Underemployment rate",
    "category": "wellbeing",
    "unit": "%", "unit_label": "%",
    "frequency": "annual",
    "source": "ABS 6202.0",
    "source_url": "https://api.data.abs.gov.au/data/LF",
    "description": "The percentage of the labour force who are employed but working fewer hours than they want and are available to work more. A more complete measure of labour market slack than unemployment alone.",
    "explainer": "Underemployment captures workers who have a job but cannot get enough hours. A retail worker on 10 hours who wants 38 hours counts as underemployed but not unemployed. The combined unemployment plus underemployment rate rarely falls below 12% even in boom times. It peaked at nearly 15% during Covid. This explains why wage growth was muted for so long despite record-low unemployment — there was more slack in the labour market than the headline rate suggested.",
    "projection_source": "RBA Statement on Monetary Policy labour market projections. Underemployment expected to remain above 6% as casual work persists.",
    "first_year": 1978,
    "last_updated": "2025",
    "projection_start": "2026",
    "notes": "ABS seasonally adjusted series. Available from 1978.",
    "series": [
      {"date":"1978","value":4.2,"projected":False},
      {"date":"1980","value":4.5,"projected":False},
      {"date":"1982","value":5.8,"projected":False},
      {"date":"1985","value":6.5,"projected":False},
      {"date":"1988","value":6.2,"projected":False},
      {"date":"1990","value":6.9,"projected":False},
      {"date":"1991","value":8.5,"projected":False},
      {"date":"1992","value":9.2,"projected":False},
      {"date":"1993","value":9.8,"projected":False},
      {"date":"1995","value":8.6,"projected":False},
      {"date":"1997","value":8.1,"projected":False},
      {"date":"2000","value":7.1,"projected":False},
      {"date":"2002","value":7.0,"projected":False},
      {"date":"2004","value":6.5,"projected":False},
      {"date":"2006","value":5.9,"projected":False},
      {"date":"2007","value":5.5,"projected":False},
      {"date":"2008","value":5.8,"projected":False},
      {"date":"2009","value":7.8,"projected":False},
      {"date":"2011","value":7.2,"projected":False},
      {"date":"2013","value":7.8,"projected":False},
      {"date":"2015","value":8.8,"projected":False},
      {"date":"2017","value":8.5,"projected":False},
      {"date":"2019","value":8.5,"projected":False},
      {"date":"2020","value":13.8,"projected":False},
      {"date":"2021","value":10.2,"projected":False},
      {"date":"2022","value":7.8,"projected":False},
      {"date":"2023","value":6.5,"projected":False},
      {"date":"2024","value":6.2,"projected":False},
      {"date":"2025","value":6.4,"projected":False},
      {"date":"2026","value":6.6,"projected":True},
      {"date":"2030","value":6.2,"projected":True},
      {"date":"2035","value":6.0,"projected":True},
    ],
  },

  # ── Electricity prices ──────────────────────────────────────────────────────
  {
    "id": "electricity_price",
    "label": "Electricity price (c/kWh)",
    "category": "economy",
    "unit": "c/kWh", "unit_label": "c",
    "frequency": "annual",
    "source": "ABS 6401.0 (CPI Electricity) / AEMC",
    "source_url": "https://www.aemc.gov.au/electricity-prices",
    "description": "Average retail electricity price in cents per kilowatt-hour for Australian households. One of the most directly felt cost-of-living indicators.",
    "explainer": "Australian electricity prices roughly tripled between 2000 and 2014, driven by gold-plating of poles and wires, carbon pricing, and rising gas prices. They then fell as rooftop solar surged and coal plants closed, before spiking again in 2022 following the Ukraine war and east coast gas shortages. Australia went from having some of the cheapest electricity in the world in the 1990s to among the most expensive by 2012. The energy transition is making prices volatile — overlaying with renewables percentage tells the full story.",
    "projection_source": "AEMC Retail Energy Price Review 2024 and AEMO Integrated System Plan projections. Assumes continued renewable buildout reduces wholesale costs but network costs remain elevated.",
    "first_year": 1980,
    "last_updated": "2025",
    "projection_start": "2026",
    "series": [
      {"date":"1980","value":4.5,"projected":False},
      {"date":"1985","value":6.2,"projected":False},
      {"date":"1990","value":8.1,"projected":False},
      {"date":"1995","value":9.8,"projected":False},
      {"date":"2000","value":12.5,"projected":False},
      {"date":"2001","value":12.8,"projected":False},
      {"date":"2002","value":13.2,"projected":False},
      {"date":"2003","value":13.8,"projected":False},
      {"date":"2004","value":14.2,"projected":False},
      {"date":"2005","value":14.8,"projected":False},
      {"date":"2006","value":15.5,"projected":False},
      {"date":"2007","value":16.5,"projected":False},
      {"date":"2008","value":18.2,"projected":False},
      {"date":"2009","value":20.5,"projected":False},
      {"date":"2010","value":23.1,"projected":False},
      {"date":"2011","value":26.8,"projected":False},
      {"date":"2012","value":29.5,"projected":False},
      {"date":"2013","value":31.2,"projected":False},
      {"date":"2014","value":32.8,"projected":False},
      {"date":"2015","value":31.5,"projected":False},
      {"date":"2016","value":30.8,"projected":False},
      {"date":"2017","value":33.5,"projected":False},
      {"date":"2018","value":36.2,"projected":False},
      {"date":"2019","value":34.8,"projected":False},
      {"date":"2020","value":33.5,"projected":False},
      {"date":"2021","value":33.2,"projected":False},
      {"date":"2022","value":35.8,"projected":False},
      {"date":"2023","value":40.2,"projected":False},
      {"date":"2024","value":40.8,"projected":False},
      {"date":"2025","value":42.1,"projected":False},
      {"date":"2026","value":43.0,"projected":True},
      {"date":"2027","value":42.5,"projected":True},
      {"date":"2028","value":41.8,"projected":True},
      {"date":"2029","value":41.0,"projected":True},
      {"date":"2030","value":40.2,"projected":True},
      {"date":"2035","value":37.5,"projected":True},
    ],
  },

  # ── Gross government debt ────────────────────────────────────────────────────
  {
    "id": "gross_govt_debt",
    "label": "Gross government debt ($bn)",
    "category": "government",
    "unit": "AUD_bn", "unit_label": "$bn",
    "frequency": "annual",
    "source": "Treasury MYEFO / AOFM",
    "source_url": "https://www.aofm.gov.au",
    "description": "Total face value of Australian Federal Government debt on issue in billions of dollars. Unlike net debt, this does not subtract government financial assets held against the borrowings.",
    "explainer": "Gross debt is the total amount the government has borrowed — the face value of all Commonwealth Government Securities (bonds) on issue, managed by the Australian Office of Financial Management. It only goes up in dollar terms, making it more alarming-looking than net debt but less analytically meaningful without context. Australia crossed $1 trillion in gross debt for the first time in 2023. Compare with net debt as % of GDP for a more accurate picture of fiscal position — at around 22% of GDP, Australia remains low by international standards despite the large absolute number.",
    "projection_source": "AOFM borrowing program and Treasury Budget 2025-26 medium term projections.",
    "first_year": 1975,
    "last_updated": "2026",
    "projection_start": "2026",
    "notes": "Gross debt does not subtract government financial assets. For fiscal position, see also Net Government Debt % GDP.",
    "series": [
      {"date":"1975","value":12,"projected":False},
      {"date":"1980","value":28,"projected":False},
      {"date":"1985","value":67,"projected":False},
      {"date":"1990","value":95,"projected":False},
      {"date":"1995","value":189,"projected":False},
      {"date":"1996","value":196,"projected":False},
      {"date":"1997","value":179,"projected":False},
      {"date":"1998","value":162,"projected":False},
      {"date":"1999","value":143,"projected":False},
      {"date":"2000","value":123,"projected":False},
      {"date":"2001","value":115,"projected":False},
      {"date":"2002","value":107,"projected":False},
      {"date":"2003","value":98,"projected":False},
      {"date":"2004","value":90,"projected":False},
      {"date":"2005","value":82,"projected":False},
      {"date":"2006","value":74,"projected":False},
      {"date":"2007","value":66,"projected":False},
      {"date":"2008","value":58,"projected":False},
      {"date":"2009","value":135,"projected":False},
      {"date":"2010","value":228,"projected":False},
      {"date":"2011","value":285,"projected":False},
      {"date":"2012","value":326,"projected":False},
      {"date":"2013","value":368,"projected":False},
      {"date":"2014","value":425,"projected":False},
      {"date":"2015","value":471,"projected":False},
      {"date":"2016","value":518,"projected":False},
      {"date":"2017","value":551,"projected":False},
      {"date":"2018","value":564,"projected":False},
      {"date":"2019","value":575,"projected":False},
      {"date":"2020","value":703,"projected":False},
      {"date":"2021","value":834,"projected":False},
      {"date":"2022","value":895,"projected":False},
      {"date":"2023","value":978,"projected":False},
      {"date":"2024","value":1020,"projected":False},
      {"date":"2025","value":1065,"projected":False},
      {"date":"2026","value":1098,"projected":True},
      {"date":"2027","value":1124,"projected":True},
      {"date":"2028","value":1145,"projected":True},
      {"date":"2029","value":1162,"projected":True},
      {"date":"2030","value":1175,"projected":True},
      {"date":"2035","value":1196,"projected":True},
    ],
  },

]

print(f"\n🇦🇺 Generating sample data for {len(indicators)} indicators...\n")
for ind in indicators:
    save(ind)

print(f"\n✅ Done. Files written to {OUTPUT_DIR}")
print("   Replace with live pipeline data when deploying.\n")
